services:
  nginx-proxy-manager:
    image: docker.io/jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: Asia/Jakarta
      DISABLE_IPV6: "true"
    ports:
      - "10.10.0.2:81:81"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
